### ISSUE TITLE
Problem when using serial terminal

### ISSUE THREAD

**Issue by virtualwiz** [google/ci_edit#174]
I tried to run ci_edit on an ARM development board. Since SSH is not available I used the serial connection.
(this may mean that the colour support of the terminal is incomplete)

Here is the traceback
![1](https://user-images.githubusercontent.com/14255046/47044916-5f09c280-d189-11e8-8b6e-376a91bba0ad.PNG)

**Comment by dschuyler** [comment]
Thanks, I'll look into it.

**Comment by dschuyler** [comment]
I've made a change that might improve this. I haven't tested in the same environment you have, so I'm not sure whether I've fixed it. Could you give it a try and let me know what happens?

I'd also be curious to know the output of 
echo $TERM
on the device.

**Comment by virtualwiz** [comment]
Many thanks for your work :)

![2](https://user-images.githubusercontent.com/14255046/47071968-dd4b8080-d1ec-11e8-9e85-019e5801d294.PNG)

It still doesn't launch in the serial terminal(whose $TERM reports 'vt220'), but I believe that this error message is a good sign.
I went to buy an ethernet cable and managed to SSH to the machine. With the SSHed xterm it works perfectly.

![tim 20181017091024](https://user-images.githubusercontent.com/14255046/47072226-88f4d080-d1ed-11e8-9104-d89d02f60ce4.jpg)

here is my setup
